version: 2

mkdocs:
  configuration: mkdocs.yml

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.12"

  jobs:
    post_create_environment:
      - pip install poetry
      - poetry env use $READTHEDOCS_VIRTUALENV_PATH/bin/python
    post_install:
      - VIRTUAL_ENV=$READTHEDOCS_VIRTUALENV_PATH python -m poetry install --only docs