version: 2

mkdocs:
  configuration: mkdocs.yml

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.12"

  jobs:
    post_create_environment:
      - echo $READTHEDOCS_VIRTUALENV_PATH
      - pip install poetry
      - poetry env use $READTHEDOCS_VIRTUALENV_PATH/bin/python
      - poetry env info
