version: 2

mkdocs:
  configuration: mkdocs.yml

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.12"

  jobs:
      post_create_environment:
        - pip install poetry  # Instala o Poetry 2.0
        - poetry config virtualenvs.create false  # Desativa a criação de ambientes virtuais pelo Poetry      
        - poetry install --only docs  # Instala as dependências di
