version: 2

mkdocs:
  configuration: mkdocs.yml

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.12"

  jobs:
      post_create_environment:
        - pip install poetry==2.0  # Instala o Poetry 2.0
        - poetry config virtualenvs.create false  # Desativa a criação de ambientes virtuais pelo Poetry      
        - poetry env use $READTHEDOCS_VIRTUALENV_PATH 
        - poetry install --only doc  # Instala as dependências diretamente do pyproject.toml
