site_name: Notas musicais
repo_url: https://github.com/Mth-Amorim/notas-musicais
repo_name: Mth-Amorim/notas-musicais
edit_uri: tree/main/docs

theme:
  name: material
  language: pt-BR
  logo: assets/logo.png
  favicon: assets/logo.png

markdown_extensions:
  - attr_list
  - admonition
extra_css:
  - stylesheets/extra.css

watch:
   - notas_musicais

plugins:
- macros
- mkdocstrings:
    handlers:
      python:
        paths: [notas_musicais]

extra:
  commands:
    run: notas-musicais